INSERT INTO instancias (idx, prem, hyp, batch_name) VALUES
(21, 'Y había echado a cinco destacamentos de U2.', 'Traté con el U2.', 'restore_2026-06-03'),
(23, 'Y había echado a cinco destacamentos de U2.', 'Trabajé con los destacamentos para el U2 todos los días durante cuarenta años.', 'restore_2026-06-03'),
(129, 'Así que, dice Bueno buscá, buscá esto en esta y esta empresa.', 'Ella no me habló.', 'restore_2026-06-03'),
(131, 'Así que, dice Bueno buscá, buscá esto en esta y esta empresa.', 'Ella me dijo que buscara su información financiera.', 'restore_2026-06-03'),
(138, 'Continué y levanté el equipaje y fui a la dirección que se suponía que debía.', 'Dejé la bolsa y pensé que no era mi problema.', 'restore_2026-06-03'),
(322, 'De modo que miro hacia arriba, descubro dónde está Ramona y ahí la llamo.', 'Llame a Ramona para saber dónde estaba.', 'restore_2026-06-03'),
(450, 'Ya se había ido y me dijo que no me preocupara.', 'Me dijo que debería asumir que la escuela estaría bien.', 'restore_2026-06-03'),
(499, 'Esta vez ni siquiera me sentía feliz de que estuviera ahí porque estaba tan estresada.', 'Estaba demasiado ansioso como para estar feliz porque ella hubiera llegado un día antes.', 'restore_2026-06-03'),
(514, 'suena muy divertido, sí, me sorprende cuántas cuántas cosas permitirían', 'Me sorprende que te dejaran entrar ahí con comida y bebida.', 'restore_2026-06-03'),
(551, 'no, de hecho ni siquiera lo conozco, no creo', 'He estado estudiando esto durante años.', 'restore_2026-06-03'),
(1197, 'Pero ser igual no es equivalente a ser el mismo, idéntico o similar.', 'Las personas iguales son idénticas entre sí.', 'restore_2026-06-03'),
(1198, 'Pero ser igual no es equivalente a ser el mismo, idéntico o similar.', 'Igualdad no significa idéntico.', 'restore_2026-06-03'),
(1199, 'Pero ser igual no es equivalente a ser el mismo, idéntico o similar.', 'Las personas únicas aún pueden ser iguales.', 'restore_2026-06-03'),
(1469, 'Los derechos se unen a los sospechosos de un crimen.', 'Las personas sospechosas de haber cometido delitos tienen estos derechos.', 'restore_2026-06-03'),
(1511, 'Pero no puedo olvidar que, cuando no era mejor que un esclavo en la casa de tu tío en Barbados, me utilizaste con una cierta amabilidad.', 'Tu tío me golpeaba duro cada día cuando me humillaba.', 'restore_2026-06-03'),
(1527, 'Los pensamientos de Bouchard alternaban entre esta y otras cosas mientras estaba ahí, en el sofá cama.', 'Bouchard tuvo un sueño irreflexivo en su lecho diurno.', 'restore_2026-06-03'),
(1545, 'Tus motivos fueron sin duda dignos... tu gratitud hacia él por librarte de los españoles.', 'Los españoles te tenían, antes de que él te liberara.', 'restore_2026-06-03'),
(1546, 'Tus motivos fueron sin duda dignos... tu gratitud hacia él por librarte de los españoles.', 'Los españoles planearon lanzarte por la borda durante la noche.', 'restore_2026-06-03'),
(1548, '¿Por qué dejaste ir a López y a los demás? Gritó con un toque de amargura.', 'Había dejado ir a López, pero se quedó con los demás.', 'restore_2026-06-03'),
(1585, 'Diga que espero con ansias conocerlo ahí. CAPÍTULO XXII.', 'Dígale que espero verlo ahí esta tarde.', 'restore_2026-06-03'),
(1586, 'Diga que espero con ansias conocerlo ahí. CAPÍTULO XXII.', 'Diga que espero con ansias encontrarlo ahí.', 'restore_2026-06-03'),
(1591, 'Creo que fue la esperanza de atrapar y colgar al Capitán Bouchard lo que hizo que mi tío dejase sus plantaciones en Barbados y aceptase el gobierno suplente de Buenos Aires.', 'Mi tío dejó sus plantaciones de Barbados antes de aceptar un puesto en Buenos Aires.', 'restore_2026-06-03'),
(1592, 'Creo que fue la esperanza de atrapar y colgar al Capitán Bouchard lo que hizo que mi tío dejase sus plantaciones en Barbados y aceptase el gobierno suplente de Buenos Aires.', 'Mi tío solía amar al Capitán Bouchard y nunca dejó sus plantaciones en Barbados.', 'restore_2026-06-03'),
(1615, 'Podés estar en lo cierto, y podés estar equivocado.', 'Puede tener razón sobre varias situaciones, pero también puede estar equivocado', 'restore_2026-06-03'),
(1640, 'En lo mío no he hecho nada de lo que me avergüence, teniendo en cuenta la provocación que recibí. Su mirada vaciló, y cayó antes que la suya tan intensa.', 'No he hecho nada de lo que me avergüence porque me provocaron mucho.', 'restore_2026-06-03'),
(1643, 'Y quizá no. La voz de López llegó lenta y burlona para responder a la confiada emoción del otro, y a medida que hablaba avanzó hacia el lado de Bouchard, un aliado inesperado.', 'López permaneció en silencio mientras se alejaba de Bouchard.', 'restore_2026-06-03'),
(1656, 'El General San Martín fue sentencioso, cómo me consta que a menudo lo era.', 'No creo que el General San Martín fuera sentencioso, ¡era tan boludo!', 'restore_2026-06-03'),
(1657, 'El San Martín fue sentencioso, cómo me consta que a menudo lo era.', 'Creo que el San Martín fue sentencioso, como solía serlo.', 'restore_2026-06-03'),
(1663, 'Pero tenía prisa por aterrizarte.', 'La persona estaba apurada.', 'restore_2026-06-03'),
(1664, 'Pero tenía prisa por aterrizarte.', 'La persona se estaba tomando su tiempo.', 'restore_2026-06-03'),
(1672, 'No te detendré más, señora.', 'No lo detendré más porque no sería justo, señora.', 'restore_2026-06-03'),
(1673, 'No te detendré más, señora.', 'Señora, estará detenida por el resto de su vida.', 'restore_2026-06-03'),
(1680, 'Él la observó pálida y tensa, con los labios entreabiertos y los ojos sorprendidos que estaban fijos en él, un testigo preocupado de esta decisión de su destino.', 'Ella se negó incluso a mirarle.', 'restore_2026-06-03'),
(1681, 'Él la observó pálida y tensa, con los labios entreabiertos y los ojos sorprendidos que estaban fijos en él, un testigo preocupado de esta decisión de su destino.', 'Tenía miedo de que la matara.', 'restore_2026-06-03'),
(1703, 'Tu estación está en el piso de armas.', 'Solo estarás parado hoy en el mazo de armas.', 'restore_2026-06-03'),
(1735, 'En su cabina a estribor, San Martín, molesto por los mismos sonidos, ya estaba levantado y vistiéndose con prisas.', 'San Martín se puso un traje de payaso en su camerino.', 'restore_2026-06-03'),
(1755, '¡Espera! Bouchard se interpuso, interrumpiéndolo, y puso una mano prohibitoria en el brazo del tirador.', 'Bouchard permitió al artillero continuar con lo que tenía que decir.', 'restore_2026-06-03'),
(1777, 'Será una bondad, lo será. Por un momento, ella se paró delante de él con una respiración acelerada, y el color menguaba y aumentaba en las mejillas.', 'Ella estaba sin aliento y por un momento parecía nerviosa.', 'restore_2026-06-03'),
(1778, 'Será una bondad, lo será. Por un momento, ella se paró delante de él con una respiración acelerada, y el color menguaba y aumentaba en las mejillas.', 'La dama estaba ansiosa porque estaba enamorada.', 'restore_2026-06-03'),
(1932, 'Me esfuerzo todo lo que puedo, dijo.', 'Ella dijo que solo da lo mejor los viernes.', 'restore_2026-06-03'),
(1946, 'Tengo algo que enseñarte.Pensativo, San Martín montó a su compañero como le fue ordenado.', 'El compañero de Don José de San Martín era un caballo.', 'restore_2026-06-03'),
(1962, 'Me pudriré en el infierno o si alguna vez sirvo al Rey, él gritó con una gran furia.', 'Yo podría servir al rey, pero eso no me haría muy feliz.', 'restore_2026-06-03'),
(1963, 'Me pudriré en el infierno antes que servir al Rey, él gritó con una gran furia.', '¡Seré feliz sirviendo al rey!', 'restore_2026-06-03'),
(2103, 'Treasure Beach es el único verdadero complejo turístico con solo un puñado de hoteles que se extienden a lo largo de tres bahías de arena.', 'No hay tantas opciones de hotel para quienes visitan la Playa del Tesoro.', 'restore_2026-06-03'),
(2104, 'Treasure Beach es el único verdadero complejo turístico con solo un puñado de hoteles que se extienden a lo largo de tres bahías de arena.', 'Hay un hotel cuatro estrellas disponible para los turistas que visiten la Playa del Tesoro.', 'restore_2026-06-03'),
(2246, 'Aun en estos primeros tiempos , se consultaba a los dioses con el oráculo emitiendo sus veredictos desde la Roca de Sibila.', 'Los dioses hablaron con el oráculo.', 'restore_2026-06-03'),
(2478, 'Lejos de la costa, se inclina un terreno lleno de pinos, mimosas, eucaliptos y brezos a una altitud de casi 915 m (3000 pies).', 'El terreno tiene cuevas.', 'restore_2026-06-03')
ON CONFLICT (idx) DO NOTHING;