INSERT INTO instancias (idx, prem, hyp) VALUES
(3177, 'Mihdhar se ha quejado de la vida en los Estados Unidos.', 'Mihdhar se quejó a varios amigos cercanos en Pakistán.'),
(4951, 'Fui criado (mis papás me hicieron del Sur) donde la estación de tren, o el depósito, era el DEE-po.', 'En el sur, las estaciones de tren se conocen como el depósito, y se pronuncia DEE-po.'),
(1022, 'En consecuencia, los adultos no necesitan enseñar a lo preescolares a fingir, como a veces lo hacen cuando los ayudan a dominar rompecabezas u otras tareas similares.', 'Los niños en edad preescolar carecen de las habilidades de modelado espacial necesarias para dominar los rompecabezas ellos solos.'),
(1415, 'Elfos o duendes a los que Anthony John Campos se refiere como gente pequeña; los pichilingues son duendes que gastan bromas malintencionadas.', 'Los duendes pequeños, dice Anthony John Campos, son todos unos bromistas engañosos, pero los elfos y los duendes no son tan listos.'),
(1628, 'Se dio cuenta de que tal vez ella misma había provocado su enojo.', 'Ella pensó que tal vez pudo haber provocado su enojo.'),
(163, 'Así que fui a su casa y luego llamé a este número al que se suponía que debía llamar cuando llegué ahí.', 'Llamé al número cuando llegué a su casa.'),
(4188, 'La sabiduría convencional sobre el género musical conocido como Ragtime continúa fluctuando.', 'La sabiduría convencional sobre el Ragtime musical continúa en aumento.'),
(489, 'Colega, parecía que tenía personalidad doble, che.', 'Estaba de mal humor.'),
(3420, 'Para los arreglos del hotel, ver informe de inteligencia, interrogatorio de Khallad, enero.', 'Más información sobre los arreglos del hotel está en el otro informe.'),
(3485, 'KSM puede haber ordenado a Binalshibh que envíe dinero a Moussaoui para ayudar a preparar a Moussaoui como potencial piloto sustituto de Jarrah.', 'KSM le dijo a Binalshibh qué hacer.'),
(3758, 'El año pasado, más de 48 000 niños del estado de Nueva York sufrieron abusos y fueron descuidados, lesionados, abusados sexualmente, negados emocionalmente, se les negó la atención y la supervisión adecuadas.', 'Solo tres niños en el estado de Nueva York fueron abusados y descuidados el año pasado.'),
(353, 'Y ella tenía tuberculosis y yo nunca me enteré de eso tampoco.', 'Sabía que estaba muy enferma de tuberculosis.'),
(3067, 'Afirmando haber sospechado de toda la transacción, el administrador se distanció de Hazmi y Mihdhar, pero no antes de que hubieran recibido la asistencia que necesitaban.', 'El administrador brindó asistencia a pesar de sus dudas.'),
(2336, 'La característica más legendaria del edificio es la veleta en forma de saltamontes.', 'Hay una veleta en la parte superior del edificio.'),
(4421, 'Las opciones no son tan atractivas.', 'Las opciones son aburridas o caras.'),
(1012, 'Y si es así, ¿a menudo están cerca de ese límite?', 'Quiero saberlo, ¿están a menudo en Inglaterra?'),
(2794, '20 Contrariamente, el desahorro o gasto superior a los ingresos actuales reduce el nivel de riqueza porque se toman cantidades ahorradas en el pasado, se venden bienes existentes o se incrementan los préstamos.', 'Gastar unos ahorros es algo muy habitual en América.'),
(4102, 'El excelente ensayo de Jacob Weisberg, Car Talk, aborda el elemento clave de las elecciones a gobernador y municipales de este año, redefine la palabra autocracia.', 'Weisberg escribió sobre perros.'),
(3507, 'Indianápolis es de verdad uno de los mejores lugares que los actores pueden visitar para trabajar para muchos', 'Los actores adoran Indianápolis por todas las agencias de casting ahí.'),
(982, 'Sí, no te sentís cómodo con ese tipo de decisión porque', '¿Por qué no estás cómodo con esa decisión?'),
(1320, 'Por lo tanto, aunque hay muchísimas proteínas diferentes, el número de formas EFECTIVAMENTE DIFERENTES solo puede ser del orden de cien millones.', 'Hay más de un millón de proteínas que tienen formas efectivamente diferentes.'),
(1292, 'Publicaciones de viajeros norteamericanos anteriores al sudoeste y a México que describen a los mexicanos no solo de forma espantosa, sino que con una pasión extrema.', 'Los primeros norteamericanos hablaban de las cosas buenas que los mexicanos españoles hicieron.'),
(4311, 'La postura de la administración Clinton es que internet debe ser una zona federal libre de impuestos.', 'El gobierno de Clinton apoya la libertad en las redes.'),
(3402, 'Véanse informes de inteligencia, interrogatorios de KSM, 1 julio de 2003; 5 de sep. de 2003.', 'Durante su interrogatorio, KSM habló sobre todo de lo que piensa del waterpolo.'),
(568, 'sí, ¿qué tipo de cachorro tenés?', '¿Qué tipo de gato rescataste?'),
(4945, 'corriendo de arriba a abajo.', 'Corriendo rápidamente arriba y abajo.'),
(306, 'Y está hablando muy rápido, está hablando por teléfono.', 'Está hablando tan despacio como puede.'),
(4398, 'El miércoles Clinton decidió hablar de una industria diferente.', 'Clinton se negó a hablar.'),
(4381, 'La gente de la Academia Internacional de las Artes y de las Ciencias Numéricas ha innovado una ingeniosa variante a este truco.', 'La gente de la escuela hizo una versión del experimento.'),
(394, 'Yo estaba como, OK, bueno, eso está bien, ya sabés, así.', 'Dije que me gustaba la nueva versión de la canción.'),
(3938, 'Las dificultades de la estructura anatómica de los elefantes hacen que lo que se considera un procedimiento común entre animales domésticos sea extremadamente problemático.', 'Es difícil operar a elefantes.'),
(1823, 'Y al instante habría recordado las palabras si hubiera podido.', 'Ella no habría recordado nada, incluso si hubiera podido.'),
(3897, 'Nuevamente, permítame felicitarlo por su nominación unánime para la membresía de Inner Circle y lo insto a que acepte este honor lo antes posible.', 'Siento decirte que nadie quería que fueras miembro del Círculo Interno.'),
(2593, 'Los prototipos fueron utilizados por las empresas comerciales durante todo el proceso de desarrollo del producto y no sólo durante la integración del producto.', 'Las empresas comerciales necesitan prototipos para mostrar su nueva tecnología al público.'),
(4791, 'Su nombre oficial era Flavian Amphitheater, el apellido de su constructor, el emperador Vespasiano.', 'Nadie sabe cómo el Anfiteatro Flavio obtuvo su nombre.'),
(342, 'En un minuto está golpeando el escritorio, al siguiente está bien, tómalo de mi escritorio, da, da, da, da, da.', 'Cambia mucho de idea.'),
(4867, 'La única referencia que tengo que menciona la tira en lo absoluto (The Penguin Book of Comics) es bastante incompleta en los detalles.', 'La referencia que tengo es incompleta.'),
(1542, 'Ella lo dejó y, después con Wolverstone, apoyado en la barandilla, observó cómo se acercaba ese bote, tripulado por una docena de marineros y comandado por una figura escarlata sentada rígidamente en el asiento de popa.', 'El barco que se acercaba estaba tripulado por una docena de marineros.'),
(4245, 'Entonces, ¿qué pasa con un plan híbrido: suscripciones para usuarios intensivos y micropagos para el resto?', 'Nadie debería pagar para usarlo.'),
(332, 'Pero a medida que fue creciendo, nunca reconoció que estaba equivocada, pero sí cambió su comportamiento.', 'Ella nunca dijo que tenía razón sobre el pastel de carne.'),
(423, 'Donde él era un, él era el hijo de un ministro, entonces él tenía, ellos tenían propiedades, y otras cosas, y estaban muy bien conectados en la comunidad y eran muy, muy estimados.', 'Su papá era un pastor luterano.'),
(3250, 'A principios de mayo de 1996, la CIA recibió información de que Bin Ladin podría estar abandonando Sudán.', 'La CIA creía que Bin Laden saldría de Sudán a principios de mayo.'),
(1529, 'Los pensamientos de Blood alternaban entre esta y otras cosas mientras estaba ahí, en el sofá cama.', 'Blood pensaba mucho en la última vez que vio a su madre.'),
(1312, 'Las casas y edificios de adobe proporcionan una sensación de seguridad y protección contra el ruido exterior con sus paredes gruesas de 2-4 pies.', 'Los nativos americanos vivían en casas de adobe.'),
(438, 'A finales de 1962, recibí órdenes de ir a Washington, DC', 'Me dijeron que fuera al DC.'),
(806, 'es es un arma automática de plástico que dispara', 'El arma está hecha de cartón.'),
(3588, 'Linda Hardwick, Directora de desarrollo y', 'Linda Hardwick Directora Ejecutiva'),
(117, 'Mi abuela solía contarme muchas historias diferentes sobre sus años de infancia y, especialmente, solía hablar sobre su familia y cómo era la vida en esa época.', 'Siempre disfrutaba escuchando las historias de mi abuela.'),
(950, 'Bueno, estoy en Texas y tenemos un profesor que murió de SIDA.', 'Nunca he estado en Texas.'),
(3375, 'Sus requisitos son mucho más modestos en tamaño y complejidad.', 'La documentación tiene menos espacios en blanco.'),
(2197, 'En las cercanías de Batu Hitam podrá encontrar una playa agradable.', 'No hay playas cerca de Batu Hitam.'),
(2221, 'Construido en los años 688-691d.C., está decorado con miles de exquisitas baldosas persas predominantemente azules y amarillas, con escrituras coránicas en los dinteles.', 'Hay un montón de pequeños azulejos ahí.'),
(3970, 'Después de un espectáculo, una pareja joven vino al escenario para saludar.', 'Una joven pareja fue a su primera actuación.'),
(2343, 'La telesilla es la favorita.', 'A todos les gusta la telesilla.'),
(3654, 'La fundación Clinton Birthplace es una organización sin ánimo de lucro 501 (c) que depende de tus contribuciones.', 'La Fundación Lugar de Nacimiento Clinton es con ánimo de lucro.'),
(2986, 'La pérdida o ganancia debería considerarse una pérdida o ganancia no intercambiable', 'Hay muchos tipos diferentes de ganancias y pérdidas.'),
(970, 'así que hay muchas cosas como esa que hace Texas Instruments y que incluso la mayoría de los empleados no sabe que hace', 'Texas Instruments fabrica bombas que son altamente secretas.'),
(3270, 'Los controladores del Washington Center estuvieron buscando el vuelo, pero no fueron informados de que buscaran ecos principales en el radar.', 'Los controladores habían visto el vuelo antes.'),
(372, 'Y era como si rechazase quién era, de algún modo, por, ya sabés, la forma en que trataba, sabés, a los otros nietos.', 'Ella trató a todos de la misma manera.'),
(4430, 'Todavía con vida a los 93, de Kooning ahora no es ni artista ni navegante de canales.', 'De Kooning es viejo.'),
(2982, 'Deberían mandarse avisos al abogado opositor y al tribunal o agencia administrativa.', 'El abogado opositor y el tribunal esperarán avisos.'),
(2875, '27 La dificultad aumenta a medida que la necesidad de modificaciones de la caldera que se han de tomar para adaptar el SCR a la instalación también aumenta.', '27 La dificultad depende de las modificaciones.'),
(1673, 'No la detendré más, señora.', 'Señora, estará detenida por el resto de su vida.'),
(3863, 'De hecho, tu historial de apoyo a la Sociedad Lowell Nussbaum paga mucho más que tu alquiler.', 'A usted se le conoce por apoyar a la Sociedad Lowell Nussbaum.'),
(4520, 'El equipo era conocido previamente por la memorable designación de Beaneaters, lo que, curiosamente, también podría considerarse un apodo indio.', 'El equipo solo ha tenido un nombre.'),
(1699, 'Eso enfriará el calor del coronel Bishop, tal vez.', 'El Coronel Bishop ya está tranquilo.'),
(14, 'Eso era lo más importante que queríamos salvar, ya que no había forma de lanzar una bomba hidrógena desde unos 30, un C124.', 'Queríamos salvar la bomba-H porque era muy difícil de manejar.'),
(687, 'El segundo que tiene es uno de los cachorros de la camada y el único macho que usó tenía un problema dental.', 'Ella no tenía cachorros.'),
(3332, 'A medida que se desvanecían todas las esperanzas de trasladar a los talibanes, se reanudó el debate sobre dar ayuda encubierta a los oponentes del régimen.', 'Se negaron a perder la esperanza de trasladar a los talibanes y acordaron hacerlo solos.'),
(783, 'fue agradable hablar con vos', 'Hablar con vos fue muy irritante.'),
(2599, 'BLM incluyó los exitosos estándares de desempeño', 'BLM puso información en el folleto.'),
(992, 'Es que tenemos casi un acre, sí, es gracioso porque tenemos um.', 'Creemos que es gracioso porque parece más que sean tres acres de tierra.'),
(4229, 'Así que llamé a U-Haul para consultar sus políticas de alquiler.', 'Me puse en contacto con U-Haul con respecto a sus contratos de alquiler.'),
(1926, 'Debo regresar al coronel Bishop para recibir mis órdenes, les dijo.', 'Dijo que no tenía que ir al Coronel Bishop para recibir órdenes.'),
(4115, 'Sin embargo, incluso en los últimos años con ganancias de USA Today, el periódico ha sido un imán para los estándares negativos de los medios de comunicación.', 'USA Today ha perdido dinero cada año recientemente, pero todavía se piensa en positivo.'),
(1930, 'En un instante, el capitán Blood vio lo que tenían en mente.', 'El Capitán Blood, por su propia vida, no podía entender qué tenían en mente.'),
(502, 'y mucho de eso es debido al hecho de que las madres son drogodependientes', 'Las madres no toman prescripciones ni medicamentos.'),
(348, 'Después estaba dando vueltas a mi rueda, no sé, parecía todo el día ese día.', 'Me apresuré y terminé rápidamente.'),
(2177, 'Aparte de las piezas fijas, la mayor parte de la música es de percusión y sirve de apoyo y refleja la acción y el estado de humor.', 'El tambor repicador está en toda la música.'),
(3251, 'A principios de mayo de 1996, la CIA recibió información de que Bin Ladin podría estar abandonando Sudán.', 'La CIA estaba segura de que Bin Laden se quedaría en Sudán por varios años.'),
(1491, 'También demuestran una reducción de la confianza en sí mismos y de la motivación, expresando dudas respecto a su propia habilidad y evitando enfrentarse a problemas.', 'Su falta de motivación y las dudas en sus habilidades provienen de fracasos pasados.'),
(3928, 'El almuerzo de alumnos de este año se celebrará el 23 de octubre de 1991, durante la reunión anual del AMRA en Nashville, Tennessee.', 'La reunión anual del AMRA se realizó en Nashville en 1991.'),
(257, 'Mmm, ¿ninguno? Dijiste que no recordás haber leído nada en particular, pero, cuando ya eras mayor en la escuela, ¿no había ningún libro que te gustara u odiaras?', 'Sé que te encantaron todos los libros que leíste.'),
(3499, 'El jefe del NCTC debe tener el rango de un director de inteligencia nacional adjunto, por ejemplo, ejecutivo de nivel II, pero bajo un título diferente.', 'El jefe del NCTC debería estar clasificado debajo de un director de inteligencia nacional adjunto.'),
(3698, 'Con su participación, podemos ayudar a los niños, como al niño chico que sale en esta página, a convertirse en mejores ciudadanos.', 'Trabajamos para ayudar a mejorar la vida de los niños.'),
(4589, 'Frente a este actitud y sorprendidos en cierto modo, los británicos confirmaron su respeto escribiendo la palabra con mayúsculas.', 'Los británicos comercializan mucho en todo el mundo.'),
(2332, 'Pasea por las cubiertas y habla con los actores que hacen las veces de marineros y peregrinos.', 'Las partes del marinero y los peregrinos son ocupadas por actores.'),
(862, 'no hay problema en absoluto y, bueno, si comprás una de estas esterillas, andá a una de esas tiendas en las que venden esterillas con ejercicios de aptitud física impresos', 'Algunas tiendas tienen colchonetas de yoga y guías de entrenamiento.'),
(4956, 'Una diferencia es que otros grupos necesitan hacerlo porque para funcionar deben asignar nuevos significados a las palabras y frases existentes o acuñar nuevas palabras y frases.', 'Algunos grupos necesitan inventarse nuevas palabras para abordar los tiempos cambiantes.'),
(2627, 'G. Las cargas de exigir a los abogados financiados de LSC que se retiren de los casos cuando el cliente abandone los Estados Unidos', 'Los abogados financiados por LSC trabajan en cualquier caso que quieran.'),
(812, 'sí, se llenan de gente muy rápido, y la gente viste un poco más elegante, es más una gente adinerada', 'Su ropa es muy elegante.'),
(4630, 'Decí: break, steak, but bleak and streak.', 'Decí curva.'),
(4484, 'El cuerpo del trabajo de Dowd como columnista y en particular las obras Flytrap con las que se ganó el Pulitzer es uno de los ejemplos más brillantes hasta ahora del autocastigo de los nacidos tras la II Guerra Mundial.', 'Además de uno de los ejemplos más brillantes del autocastigo de los nacidos tras la II Guerra Mundial, el cuerpo laboral de Dowd incluye muchas columnas sobre el enjuiciamiento de ecologistas radicales.'),
(4189, 'La sabiduría convencional sobre el género musical conocido como Ragtime continúa fluctuando.', 'La sabiduría convencional sobre el Ragtime musical no es constante.'),
(2268, 'La Estampida estaba pensado originalmente para mostrar todas las técnicas y emoción de reunir ganado en las praderas.', 'La Estampida no tuvo nada que ver con el ganado.'),
(3211, 'Las series incluían también Operation Infinite Resolve, una diversidad de ataques propuestos de seguimiento en los objetivos de Al Qaeda en Afganistán.', 'No hubo planes disponibles para dar seguimiento a los objetivos en Afganistán.'),
(3117, 'Investigadores del FBI han especulado con que Al Qaeda podría haber mandado a otros extremistas musulmanes en la zona de Phoenix tomar parte en entrenamientos de aviación.', 'Investigadores del FBI encontraron otros 100 extremistas en Phoenix.'),
(4638, '(Se ha dicho, no del todo en broma, que si a los japoneses se le exigiera pagar una tarifa de licencia por cada palabra en inglés que utilizan, su superávit comercial desaparecería.)', 'Los nombres propios a menudo se usan en exceso cuando se traduce al inglés de idiomas extranjeros.'),
(311, 'No me puedo acordar de lo que fue, pero de repente me puse muy nervioso pensando que iba a ir a la escuela por primera vez y probablemente este fue el día más estresante de mi vida.', 'Estaba preocupado por empezar el jardín de infantes'),
(1102, 'Por otro lado, las partículas y las tres fuerzas no gravitacionales todavía tienen que incorporarse a una imagen de red de giro.', 'Las partículas ya se habían incorporado.'),
(1088, 'El tribunal utilizó 6 veces este poder con moderación en los cincuenta y cinco años previos a la Guerra Civil.', 'La Corte utilizó este poder 5 millones de veces en los cincuenta y cinco años previos a la Guerra Civil.'),
(2223, 'Observe cómo la pintura trampantojo en el bajo techo arqueado aspira a convertir la pequeña iglesia en una excelsa catedral gótica.', 'La pintura aspira a convertir la iglesia en una catedral gótica.'),
(1125, 'Son de un pequeño pueblo de San Agustín Acolman, que se encuentra cerca de las pirámides de Teotihuacan.', 'San Augustin Acolman tiene menos de 1,000 residentes.'),
(3902, 'Tu generosidad ayudará al IRT a seguir informando de las mejores historias de la mejor manera posible.', 'Su contribución ayudará al IRT.'),
(3585, 'Nombre de la organización (si se aplica), Dirección, Ciudad, Estado, CP', 'Si está disponible, liste el nombre de la organización junto con la dirección completa.'),
(3912, 'Es importante y esperamos que haga una contribución considerable al fondo de la Búsqueda de la Excelencia este año.', 'Este año el fondo Pursuit of Excellence está lleno de donaciones, por favor, considere donar a otro fondo.'),
(2326, 'Durante la Depresión, fue la provincia más pobre del país, cerca de la inanición.', 'La provincia estuvo cerca del hambre durante la Depresión.'),
(3628, 'conseguiremos la meta.', 'Lograremos nuestras aspiraciones.'),
(20, 'Esta es Estela Flono. Creció en Ag-- Augusta, GA, y va a hablar sobre algunas historias de su infancia.', 'Estela Flono pudo hablarnos hoy a pesar de su apretada agenda.'),
(2646, 'Las emisiones de mercurio contribuyen a que el mercurio se deposite en el agua.', 'Las emisiones de mercurio crean problemas en el agua, que luego es ingerido por los peces.'),
(2108, 'Después viene Bona, un centro de cestería que también se anuncia como el hogar de la danza kecak.', 'El baile de kecak no es de Bona.'),
(2930, 'En primer lugar, el ED potencialmente proporciona un momento ideal de aprendizaje para los pacientes que tienen problemas con el consumo de alcohol.', 'El ED desencadena una recaída en el abuso de alcohol en pacientes en recuperación.'),
(4891, 'Se pide el despido de la sección 8 por la cagada incorregible de esta empresa.', 'Esa persona está siendo dada de baja de manera honorable.'),
(1316, 'Las pachucas eran las novias de los pachucos, pero también tenían un estilo de vestir propio.', 'Las Pachucas llevaban más ropas que los Pachucos.'),
(4813, 'Un segmento de las fuerzas armadas es el Batallón de la Construcción, que fue rápidamente abreviado como C.B.', 'El Batallón de la Construcción es una de las ramas más importantes de las fuerzas armadas.'),
(2497, 'Esto es nuevo para Hungría, y tendrás que ir manejando un rato por las afueras si querés jugar.', 'Hay varios lugares en la ciudad donde la gente nueva puede jugar.'),
(4603, 'Un nuevo morfema sobrevive a la novedad de su primera innovación (como telethon para -athon), ya que resulta ser útil casi por accidente, y da algo nuevo a la expresión.', 'Las nuevas palabras son elegidas por un comité de idiomas y su uso es obligatorio.'),
(452, 'Ya se había ido y me dijo que no me preocupara.', 'Dijo que era hora de entrar en pánico.'),
(41, 'Hoy nos hablará sobre la Tercera SS, el U2 Quick y el Blackbird.', 'Él habla de tres cosas.'),
(2603, 'Por ejemplo, una capital de estado que visitamos es el hogar de más de 600 compañías de software.', 'Las compañías de software evitan capitales por razones legales.'),
(673, 'Sí, simplemente no parece posible, ¿verdad?', 'La verdad es que no parece que pueda pasar.'),
(2789, 'Las contribuciones del empleador y del empleado se calculan generalmente de la misma manera', 'Por lo general, la contribución del empleador es mayor que la contribución del empleado.'),
(526, 'Sí, personas que podrían estar en el trabajo en cualquier momento o cuyas decisiones podrían nublarse si tuvieran que tomar una decisión.', 'Sí, gente que quizás no tenga hambre.'),
(1657, 'El Sr. Julián fue sentencioso, cómo me consta que a menudo lo era.', 'Creo que el señor Julian fue sentencioso, como solía serlo.'),
(357, 'Empecé de inmediato, eh, entrenando con los otros dos muchachos que estaban en el lugar.', 'Nunca recibí entrenamiento, así que lo fui descubriendo a medida que avanzaba.'),
(3349, 'Haznawi (vuelo 93) y Wail al Shehri (vuelo 11) llegaron a Miami desde Londres el 8 de junio de 2001 utilizando la misma ruta que los tres anteriores.', 'Ambos vuelos aterrizaron en Miami el 8 de junio de 2001.'),
(1298, 'Esta es la manera en la que vivimos hoy. Gehry parece estar diciendo, ¿por qué no la disfrutamos?', 'Gehry parece decir disfrutar de la vida.'),
(4410, 'Los liberales negros, como los profesores Henry Louis Gates y Cornel West, mantienen la fe integracionista. Junto a ellos está el economista negro Glenn Loury, un conservador que rompió filas para respaldar la acción afirmativa como una política necesaria.', 'Glenn Loury es un conservador.'),
(2533, 'Otros esfuerzos que se están realizando ahora o que se han planeado incluyen el', 'No hemos planeado nada más para el futuro.'),
(4320, 'La creencia popular en Washington esta semana es que los escritores jóvenes como Glass, que se quiebran, merecen simpatía, porque el sistema les empuja a ser estrellas antes de ser obreros.', 'Glass es un pintor.'),
(1623, '¡Así que te contaron sobre eso!', '¡Entonces no te informaron sobre nuestra situación!'),
(3401, 'Antes del 9/11, ninguna agencia del gobierno de los E.U. analizó sistemáticamente las estrategias de viaje de los terroristas.', 'Las estrategias de los viajes terroristas no se analizaron sistemáticamente hasta el 11 de septiembre.'),
(1834, 'Se dirigió a Lord Julian.', 'Se lo arrojó al señor Julian.'),
(742, 'Sé que todos están siempre ocupados y preocupados, y que la gente tiene muchos problemas y no se sientan sin más a hablarlo sabiendo que todo va a salir bien', 'De hecho, solo unas pocas personas hablarán de sus problemas actuales.'),
(1893, 'Si estás pensando en tocar las fibras sensibles del obispo, sos un tonto más grande de lo que siempre había pensado, Lorenzo. Vos estabas con todo menos con pistolas.', 'Si Lorenzo fuera listo, habría hecho que el obispo se enamorara de él.'),
(636, 'lo hacen como un trabajo de amor, por lo que la idea del oficial es buena', 'No soporto la idea de ser directivo.'),
(1348, 'Los arabescos y las volutas de las molduras y los ornamentos arquitectónicos en un salón francés reflejaban los volantes que adornaban los vestidos de las mujeres y los volantes de las camisas de los hombres.', 'Los vestidos de las mujeres tenían cintas.'),
(405, 'De todos modos, se les ocurrió esta invención del alto regulador de O2.', 'Ellos inventaron un nuevo regulador.'),
(131, 'Así que, dice Bueno buscá, buscá esto en esta y esta empresa.', 'Ella me dijo que buscara su información financiera.'),
(312, 'Eh, vivía a las afuera de St. Louis, entre Jefferson City y St. Louis, MO.', 'Viví en Texas.'),
(1343, '96 Y los padres y entrenadores que critican en lugar de alentar y no permiten que los jugadores se olviden de la derrota, provocan ansiedad intensa en algunos chicos.', 'Algunos entrenadores causan ansiedad.'),
(2049, 'Asimilándose más fácilmente con la comunidad anglosajona, solo las escuelas protestantes aceptaron que sus hijos judíos de Europa del Este se graduaran en el acaudalado Westmount o emigraran, de nuevo, a Toronto.', 'Los judíos de Europa del Este se adaptan bien a todo el mundo.'),
(689, 'El segundo que tiene es uno de los cachorros de la camada y el único macho que usó tenía un problema dental.', 'Había un total de 8 en la camada, solo el macho tenía problemas dentales.'),
(4483, 'El cuerpo del trabajo de Dowd como columnista y en particular las obras Flytrap con las que se ganó el Pulitzer es uno de los ejemplos más brillantes hasta ahora sobre la explosión del autocastigo boomer.', 'Para ver ejemplos brillantes de auto castigo de la generación boomer, no busque más allá de las obras Flytrap ganadoras de Pulitzer de Dowd y, en realidad, en la mayor parte de su trabajo como columnista.'),
(1443, 'Un vínculo cálido entre padres e hijos basado en la cooperación es especialmente vital para ayudar a los niños recalcitrantes a internalizar los estándares de los padres.', 'Los niños que crecen rodeados de padres siempre son problemáticos.'),
(1750, 'Su mano se cerró sobre la culata de una de las pistolas colgadas ante él.', 'Había perdido su arma y no la llevaba encima.'),
(2274, 'El Beaux Arts Ayuntamiento ha sido reemplazado por el Centro Gubernamental cercano.', 'El ayuntamiento fue reemplazado por un centro gubernamental.'),
(849, 'eh, nunca organicé uno, pero tenemos uno, vamos a tener uno en el Día de los Caídos, supongo que tuvieron uno en los últimos dos años', 'Lo hacen todos los años para el Día de los Caídos.'),
(4575, '«Vanilla», extraída de las vainas de una planta tropical, fue un préstamo del español «vainilla», que nombraba la flor, la semilla o el sabor.', 'La vainilla sale de una planta tropical.'),
(3406, 'Nunca fue objeto de una deliberación oficial entre organismos.', 'Las agencias establecieron numerosos paneles para evaluar el tema formalmente.')
ON CONFLICT (idx) DO NOTHING;pus