INSERT INTO instancias (idx, prem, hyp) VALUES
(2496, 'Esto es nuevo para Hungría, y tendrás que ir manejando un rato por las afueras si querés jugar.', 'La ubicación de la obra está a una hora en auto.'),
(3400, 'Antes del 9/11, ninguna agencia del gobierno de los E.U. analizó sistemáticamente las estrategias de viaje de los terroristas.', 'Las estrategias de viaje terrorista fueron una fuente importante de estudio del gobierno antes del 11 de septiembre.'),
(4613, 'En los patios de las escuelas el ruido más fuerte-- bullicio --está cesando.', 'Hay mucho menos ruido en los patios de la escuela últimamente.'),
(602, 'y ahora tengo una hermana en Alemania', 'Tengo una hermana que habla alemán.'),
(2472, 'Bajo el altar, un disco de plata rodea un agujero que marca el lugar en el que, según la tradición, la cruz de Jesús se irguió junto con las de los dos ladrones a cada lado.', 'Los hombres al lado de Jesús eran malas personas.'),
(580, 'sabés, todos mis hijos son geniales, muy buenos, y creo que no, aprende de los niños mayores también, pero', 'Estoy muy orgulloso de lo mucho que mis hijos saben.'),
(952, 'sí, y cualquier momento en el que intentés ir al, este... los acomodadores siempre te dirían que volvieras', 'Los acomodadores no te dejan pasar al siguiente nivel del estadio.'),
(4326, 'Para cantar que venga la buena fortuna a aquellos a los que temo,', 'Espero que esas personas a las que tengo miedo tengan buena suerte.'),
(4326, 'Para cantar que venga la buena fortuna a aquellos a los que temo,', 'Espero que esas personas a las tengo miedo tengan buena suerte.'),
(966, 'No consigo acordarme, solo hice esto una vez antes.', '¡Hice esto un millón de veces!'),
(966, 'No consigo acordarme, solo hice esto una vez antes.', '¡Hice esto un millón de veces!'),
(1800, 'Ya sabés, Pedro, que solo Lord Julian se ha interpuesto entre Bishop y su odio hacia vos.', 'Pedro es odiado por el Obispo.'),
(4926, 'Pero, de hecho, estaría fingiendo ingenuidad al afirmar que ahora se entiende que al referirse a los ''hombres'', en general, se incluye también a las mujeres.', 'Los hombres sólo se refieren a lo masculino.'),
(1800, 'Ya sabés, Pedro, que solo Lord Julian se ha interpuesto entre Bishop y su odio hacia vos.', 'Pedro es odiado por el Obispo.'),
(374, 'Y era como si rechazase quién era, de algún modo, por, ya sabés, la forma en que trataba, sabés, a los otros nietos.', 'Trataba a los otros nietos de forma diferente porque eran negros.'),
(4926, 'Pero, de hecho, estaría fingiendo ingenuidad al afirmar que ahora se entiende que al referirse a los ''hombres'', en general, se incluye también a las mujeres.', 'Los hombres sólo se refieren a lo masculino.'),
(1221, 'El final del siglo XVIII fue de hecho un tiempo maravillosamente simplista.', 'Alguien recuerda finales del siglo XVIII.'),
(374, 'Y era como si rechazase quién era, de algún modo, por, ya sabes, la forma en que trataba, sabes, a los otros nietos.', 'Trataba a los otros nietos de forma diferente porque eran negros.'),
(1381, 'La mayoría de las casas tendrán un nacimiento preparado para las oraciones y los cantantes.', 'Las escenas de nacimientos son muy complejas.'),
(1221, 'El final del siglo XVIII fue de hecho un tiempo maravillosamente simplista.', 'Alguien recuerda finales del siglo XVIII.'),
(2906, 'Los bomberos del condado de Baltimore no tienen un programa formal para proporcionar un impulso financiero a los bomberos y paramédicos que están lesionados y no pueden trabajar.', 'Debería existir un programa para compensar a estos funcionarios.'),
(1381, 'La mayoría de las casas tendrán un nacimiento preparado para las oraciones y los villancicos.', 'Las escenas de nacimientos son muy complejas.'),
(3742, '¡Es hora de la famosa ÚLTIMA LLAMADA!', '¡Es hora de la última llamada!'),
(1645, 'Entonces solo fuiste un caballero desafortunado.', 'En el pasado eras un caballero desafortunado.'),
(2906, 'Los bomberos del condado de Baltimore no tienen un programa formal para proporcionar un impulso financiero a los bomberos y paramédicos que están lesionados y no pueden trabajar.', 'Debería existir un programa para compensar a estos funcionarios.'),
(3742, '¡Es hora de la famosa ÚLTIMA LLAMADA!', '¡Es hora de la última llamada!'),
(1626, 'Se dio cuenta de que tal vez ella misma había provocado su enojo.', 'Estaba enojado porque ella siempre habla demasiado.'),
(266, 'El presidente Kennedy dice a los pilotos, dice, ''Caballeros, hacen buenas fotos''.', 'Kennedy habló con los pilotos.'),
(1645, 'Entonces solo fuiste un caballero desafortunado.', 'En el pasado eras un caballero desafortunado.'),
(1626, 'Se dio cuenta de que tal vez ella misma había provocado su enojo.', 'Estaba enojado porque ella siempre habla demasiado.'),
(155, 'Esta fue la primera vez que, eso había sucedido en 75 años, la legislatura de Texas había votado una unidad militar siendo Embajadores de Texas, por lo tanto, necesitaba embajadores de Texas.', 'La unidad militar fue llamada Embajadores TX.'),
(266, 'El presidente Kennedy dice a los pilotos, dice, ''Caballeros, hacen buenas fotos''.', 'Kennedy habló con los pilotos.'),
(1631, 'Siempre estaré agradecido.', 'Estaré por siempre lleno de malicia y odio.'),
(419, 'No me importa cómo lo hagas.', 'Necesito saber exactamente cómo harás esto.'),
(155, 'Esta fue la primera vez que, eso había sucedido en 75 años, la legislatura de Texas había votado una unidad militar siendo Embajadores de Texas, por lo tanto, necesitaba embajadores de Texas.', 'La unidad militar fue llamada Embajadores TX.'),
(1631, 'Siempre estaré agradecido.', 'Estaré por siempre lleno de malicia y odio.'),
(877, 'la mayor parte del tiempo cuando usted ve el colectivo uh usted sabe, los colectivos con el diésel, esto es uh aquellos son partículas de carbón y el dióxido de carbono uh y el vapor', 'Los colectivos funcionan con combustible diésel.'),
(419, 'No me importa cómo lo hacés.', 'Necesito saber exactamente cómo harás esto.'),
(3351, 'En la lucha contra el terrorismo, estas distinciones parecen cada vez más artificiales.', 'Las distinciones parecen verdaderamente genuinas.'),
(194, 'Se vive y se aprende, ya sabés, cuando probás, eh, avión.', 'Hacer pruebas en aviones te enseña a gestionar la presión.'),
(877, 'la mayor parte del tiempo cuando usted ve el colectivo uh usted sabe, los colectivos con el diésel, esto es uh aquellos son partículas de carbón y el dióxido de carbono uh y el vapor', 'Los colectivos funcionan con combustible diésel.'),
(2231, 'Los pescadores de río deben disponer de un permiso. Infórmese en la oficina de turismo más cercana para conseguirlo.', 'Tenés que tener un permiso para pescar peces de más de 6 pulgadas.'),
(3351, 'En la lucha contra el terrorismo, estas distinciones parecen cada vez más artificiales.', 'Las distinciones parecen verdaderamente genuinas.'),
(3930, '¿CUÁL ES EL DESAFÍO DE LOS MAYORES?', 'Hay un desafío para las personas mayores.'),
(194, 'Se vive y se aprende, ya sabés, cuando probás, eh, avión.', 'Hacer pruebas en aviones te enseña a gestionar la presión.'),
(2231, 'Los pescadores de río deben disponer de un permiso. Infórmese en la oficina de turismo más cercana para conseguirlo.', 'Tenés que tener un permiso para pescar peces de más de 6 pulgadas.'),
(2755, '24 Estas características también serían apropiadas para los informes de responsabilidad del GMRA.', 'Hay otras características que también podrían usarse para los informes.'),
(3930, '¿CUÁL ES EL DESAFÍO PARA LAS PERSONAS MAYORES?', 'Hay un desafío para las personas mayores.'),
(4817, 'En este caso, Skeat no ignorará esta nota y repetirá la ofensa en algún momento futuro.', 'Skeat estudiará la nota todos los días.'),
(2755, '24 Estas características también serían apropiadas para los informes de responsabilidad del GMRA.', 'Hay otras características que también podrían usarse para los informes.'),
(786, 'oh, ya veo, el estado no lo necesita, es como... es bastante... es bastante inusual, ¿no?', 'Incluso si no es obligatorio, debe hacerse.'),
(4817, 'En este caso, Skeat no ignorará esta nota y repetirá la ofensa en algún momento futuro.', 'Skeat estudiará la nota todos los días.'),
(786, 'oh, ya veo, el estado no lo necesita, es como... es bastante... es bastante inusual, ¿no?', 'Incluso si no es obligatorio, debe hacerse.')
ON CONFLICT (idx) DO NOTHING;